version: '3.5'
services:
  portal-d:
    image: btcag/btc-np-runtime:6.5
    container_name: btc-np-d-portal
    restart: always
    volumes:
      - ../netzportal-d:/opt/simplifier/data
#    ports:
#      - 6080:8080
    environment:
      - DB=mysql
      - MYSQL_HOST=btc-np-db
      - MYSQL_PORT=3306
      - MYSQL_USER=${BTC_NP_D_DBUSER}
      - MYSQL_PASSWORD=${BTC_NP_D_DBPWD}
      - MYSQL_DB=${BTC_NP_D_DBNAME}
      - PLUGINLIST=keyValueStorePlugin,pdfPlugin,captcha,contentRepoPlugin,jsonStore,${BTC_NP_D_PLUGINLIST}
      - VIRTUAL_HOST=127.0.0.1
    networks:
      - private-network-d
      - public-network
    depends_on:
      - db
#  watchtower:
#    image: containrrr/watchtower
#    container_name: btc-np-d-watch
#    command: --cleanup --schedule "0 0 0 * * *"
#    restart: unless-stopped
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock      
networks:
  private-network-d:
    internal: true      
  public-network:
